### ISSUE TITLE
Cmake error while build 

### ISSUE THREAD

**Issue by bob44burg** [Samsung/UTopia#18]
hey guys. i am facing issues while building  UTopia locally. I was wondering if you can help me out with this cmake error I keep getting.``

cmake -B build -S . -DBUILD_TESTING=false
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- !!!NOT DEFINED LLVM_DIR, USE DEFAULT VALUE
-- !!!LLVM_DIR: /usr
-- Build type is not set. Using debug as default.
-- Found LLVM 10.0.1
-- Using LLVMConfig.cmake in: /usr/lib/llvm-10/cmake
-- Linker detection: unknown
LLVM STATUS:
  Definitions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
  Includes    /usr/lib/llvm-10/include
              /usr/lib/llvm-10/include
  Libraries   /usr/lib/llvm-10/lib
  LLVM_CMAKE_DIR: /usr/lib/llvm-10/lib/cmake/llvm
  AddLLVM: 
CMake Error at external/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /workspace/work/UTopia/external/spdlog

  does not contain a CMakeLists.txt file.

CMake Error at lib/target_analysis/CMakeLists.txt:3 (add_subdirectory):
  add_subdirectory given source "targetpb" which is not an existing
  directory.

-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!
See also "/workspace/work/UTopia/build/CMakeFiles/CMakeOutput.log".

Also , I have build the docker image but when I run docker run -p 8080:80 utopia, nothing happens.

**Comment by sole2** [comment]
Hello @bob44burg.
> CMake Error at external/CMakeLists.txt:3 (add_subdirectory):
  The source directory
    /workspace/work/UTopia/external/spdlog
  does not contain a CMakeLists.txt file.

UTopia contains spdlog as submodule. It should be downloaded before build. Please download it with this command `git submodule update --init`.

>CMake Error at lib/target_analysis/CMakeLists.txt:3 (add_subdirectory):
add_subdirectory given source "targetpb" which is not an existing
directory.

Sorry, current latest code have some problems. Please use working commit 571a769 or retry after #19 is merged.

> Also , I have build the docker image but when I run docker run -p 8080:80 utopia, nothing happens.

Docker image is for build/run UTopia inside. There is no startup command, nothing happening is normal.

**Comment by bob44burg** [comment]
thanks for the such a quick response. I will wait for the fix to get merge @sole2

**Comment by sole2** [comment]
PR merged! 😄
