### ISSUE TITLE
Where can I find a built fuzz driver?

### ISSUE THREAD

**Issue by vsecv** [Samsung/UTopia#26]
Hello,

Where can I find a built fuzz driver?

Is the file created in the path below?

```
exp/cpuinfo/lib/output/profiles/
```

Do I have to run multiple files individually? Can't I run tests at once?

```
rwxr-xr-x 1 root root 40185960 Mar 21 10:13 BRAND_STRING_amd_Test
-rwxr-xr-x 1 root root 40670824 Mar 21 10:13 BRAND_STRING_intel_Test
-rwxr-xr-x 1 root root 40005472 Mar 21 10:13 BRAND_STRING_intel_android_Test
-rwxr-xr-x 1 root root 39612160 Mar 21 10:13 BRAND_STRING_other_Test
-rwxr-xr-x 1 root root 39584200 Mar 21 10:14 BRAND_STRING_transmeta_Test
-rwxr-xr-x 1 root root 39693192 Mar 21 10:14 BRAND_STRING_via_Test
-rwxr-xr-x 1 root root 41007424 Mar 21 10:14 CLUSTER_consistent_cores_Test
-rwxr-xr-x 1 root root 41007424 Mar 21 10:15 CLUSTER_consistent_cpuid_Test
...
...
```

Thanks

**Comment by yuweol** [comment]
You can find the built fuzzers in exp/cpuinfo/lib/output/fuzzers if you use the helper script to generate fuzzers. The directory exp/cpuinfo/lib/output/profile is used to measure coverage.

And yes, you should run each fuzzer individually. So far, we have not planned to provide a script to run them all at once.
