### ISSUE TITLE
How to create a test case to recreate a collision

### ISSUE THREAD

**Issue by vsecv** [Samsung/UTopia#27]
Hello,

I'm curious about how to reproduce the collision.

If the crash file as below occurs, the code for reproduction must be rewritten.

```
$ cat crash-11c4d16e353846802c27ab0bc9ba04cb3326cc3e
fuzzvar2910: "test17Au\001\022tofuzzExgt"
```

Do I need to manually analyze and write a test code?

Or is there a separate add-on?

Thanks.

**Comment by yuweol** [comment]
As I remember, you can reproduce crash simply by passing the crash file as an argument to the fuzzer.
For example, if that crash was found while fuzzer 'A' worked, then script for reproduction would be like below.
`./A crash-11c4d16e353846802c27ab0bc9ba04cb3326cc3e`

**Comment by vsecv** [comment]
@yuweol It would be nice to have a separate reproduction test code to pass it to the developer. Looking at the trophy, I think I wrote a separate code for reproduction. Reproduction code for reporting to developers, not fuzzers.

**Comment by yuweol** [comment]
I agree. It seems necessary to write reproduction code that is friendly to the developer. Unfortunately, writing such code falls outside the scope of this project, so it needs to be done manually.
