### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by rhezashan** [Samsung/UTopia#7]
Hi,
I ran this command and docker has failed to build 
docker buildx build -f docker/Dockerfile -t utopia .
`ERROR [8/8] COPY --chmod=755 base/hooks /usr/local/bin/`

------
 > [8/8] COPY --chmod=755 base/hooks /usr/local/bin/:
------
error: failed to solve: failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount592784374/base: lstat /var/lib/docker/tmp/buildkit-mount592784374/base: no such file or directory

Can you tell me how to fix this?

**Comment by sole2** [comment]
@rhezashan 
Hello. Thank you for reporting!
There was typo in Dockerfile. Sorry.
I created #8 for fixing it. It will works well after merge.

**Comment by rhezashan** [comment]
Thanks for looking this issue!
